language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mgeiger
  password:
    secure: M3Ld5d5GCrErbGNxPG7S9bV/s17Y86BmFLU1mBH78HqKSoc1bfSYzUDeLxncpA59vfSrq9D3TaHPpLGzbYBQjDdFdeWxMQhZC8u3Be77PRQ/eDioRIyb/2k99PpAks/R4ItXRSGNjwwV3HWlYsFRST1gyvHfEV4Mjp6uui2ioIE/0RW2GDAYbkllxXrPeplxdTt08XdTfGXZKn6xZJdgfkM1mchO9IIRILZQnim7kbQKq0BRbCg+j3SopBgvmlDClwm88/0d+2xZcTWoTIflSe1AqMLETCWfHfeFd1YfP/g1JcEczmngKli96Mt8svqi2VzVmoqDKz82Ck++00bS3kaHVr0ASHgl8RB4/k/gOiSPa7OmlUhSqHpdvkLmko2Amb3lIf/AKIukhwCHGuJXgbyTS+uyDP5SjEHUu5zTpTSrmThJcTBMsoMJsRFKkc5P/g2RQskJ+/L2JC8lAbzccS17K9K62Os7LiA5N328MJtrAu8AJh6GxiMud2oksgpLz7fZ7hzoNvJA2o364QQqCcHDAQf1YA1RZT6ZLIND3J57ay4Z6qHpHwjjadqRFLigjYTjxk4hEQ5wni3PSpUO9v5V3ECbdAbHbyykjM7IfOWjZzAZ5kSe3tP/4E5j6+4rUFPW7RgmunZ+YWpGgAoCbpoNLPsgl4M+lMNg+YZmV9k=
  on:
    tags: true
    repo: mgeiger/tekpower
    python: 3.6
notifications:
  slack:
    secure: RruAcJGOD7qQI29aKL7S18Ankl5CJbOZnqPwDyxcV6wJJtWirjA55A8ZrHji98j6rO3WHBovlxVNvdiohvU1iiyk12ZekV9DTXR7uPpmLWy50LOjSEdcQbAxQ7M/BjbktoZy3NMBU/48nh/RoSHeTBRTNgi1iE/63XwuA0OM6jodO128cG/XfP0QcZN+/BHImMqRyZDYzzTuL3x3fyILEQ93ig/kfltWUSprY9DTj5os8wyrR3Oj8Kpo4Ys0RzYVpv2gJa9jtEh5VXrxFql3SJLWJPtr4/cY6qX+CQTsUqB3BBfKlOb9fsv+zz2q09SpFKOHIrocZXgOVYv56viUaxA1Po2/TNAPefS4F3vLmGSq/myb4yWOJivk9gP+wL1XgokDsunetzM9BbELTWAngDTsFagSesom50BJDMIH4AIq7HSeGjlfxQ1XEBM/OkJOYMW58gd/q9FzZgwSAMBm5sjfqfRwQvBdXh02fM4lb12YRMqWLmFxvyGvn0t1JmEJwy0fU9PJ/DCBTwTEhOjAVoB3MLMlz9sBTJBpH/icv1HiK8dbjjxGtZaA6U+o1wCfV0MFs2cCEFvCcfyNdQpBiEO3QQCAklBqT8dE5omjA/aozb4o0wurxTBbKzJleIeOYNje0aw0heFSQE3MImgp5cS1DRpg/WPTzdmd73i/3BE=
    on_success: change
    on_failure: always

